class Constant {
    static navigation = undefined
    static screenName=undefined
    static accessToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjJsd2NZSWJtVVtTX1Q3UU4wb3N2NUEkJCIsImZpcnN0TmFtZSI6InNhbiIsImxhc3ROYW1lIjoiZGlwIiwiZW1haWwiOiJhZHNkc0BrZXViaWsuY29tIiwibW9iaWxlTnVtYmVyIjo5ODcwNTA5NTQ5LCJkZXZpY2UiOiIyIiwiZGV2aWNlSWQiOiJ6eGN2Ym5tcWFzZGYiLCJidWlsZCI6ImFzZGZnaHFzeGRjZnZnYiIsInByZWZlcnJlZE1hbGxJZCI6NywiaXNFeGNsdXNpdmUiOjAsIndoYXRzQXBwQ29uY2VudCI6IiIsIm9wdGVkRm9yRGVsZXRpb24iOjAsInJlYWN0aXZhdGlvbkNvZGUiOm51bGwsInByb2ZpbGVQaWMiOiJodHRwczovL3B1YmxpYy1mdXR1cmVyZXRhaWwtZGF0YS5zMy5hbWF6b25hd3MuY29tL3Byb2ZpbGVQaWMvODk4MDMwMDY1MzktMS0yMDIwLTgtMjYucG5nIiwibGFzdExvZ2luIjoiMDMtMDItMjAyMyIsImRlbGV0aW9uUmVxdWVzdGVkQXQiOm51bGwsImlhdCI6MTY3NTQyMDIyNCwiZXhwIjoxNjc2NzE2MjI0fQ.UUwep91qFqlieWj72Sf0GYBXwbJfpjSHaz67NcDt5lw"
}
export default Constant