const colors = {
    black:'black',
    white:'white',
    red:'red',
    yellow:'yellow',
    transplant:'transplant',
    gray:'gray',
    blue:'blue',
    light_blue:'light_blue',
    iris_blue:'#5D3FD3',
    disable_txt_color:"#BABABA",
    txt_color:"#434343",
    txtGray:'#909090',
    appBackground:"#F5F5F5",
    offWhite:"#E6E9EB",
    greyTextColor:'#6F6F6F',
    highLightedText:"#00ACEF",
    buttonPrimary:'#003549',
    dividerColor:'#E8E8E8',
    swipeBackground: "#E6E9EB",
  offerText: "#737171",
  red: "#C20000",
  highLightedText: "#007DBA",
  green: "#318E65",
}
export default colors;
