const screenName = {
    SPLASH:'Splash',
    HOME:'Home',
    SURVEY:'Survey',
    LOYALTYHUB:'LoyaltyHub',
    EARNTOUNLOCKLOYALTY:'EarnToUnlock',
    SCRATCHCARD:'ScratchCard',
    SPIN_WHEEL_LIST:'SpinWheelList',
    DINE_ND_WIN:'DineNDWin',
    LOGIN:'Login',
    OTP:'OTP',
    SCRATCHCARDLIST: "ScratchCardList",
    OFFERLIST: "OfferList",
    OFFERDETAILS: "OfferDetails",
    PROFILE: "Profile",
    PROFILEDETAILS: "ProfileDetails",
    HELP: "Help",
    DELETEACCOUNT: "Delete Account",
    SUBMITDELETE: "Submit Delete",
    DELETESUCCESSFUL: "Delete Successful",
    FEED_MEDIA_DETAILS:'FeedMediaDetails',
    VIDEO_PLAYER:'VideoPlayer',
    FEED_TAB:'FeedTab',
    BRAND_DETAILS:'BrandDetails',
}
export default screenName;
