const strings = {
  login: 'Login',
  confirm: 'Confirm',
  register: 'Register',
  mobile_no: 'Number',
  app_name: "Phoenix Nhance",
  login_des: "Please enter mobile number for send verification code to Register our app",
  country_code_val: '+91',
  otp_des: 'Please enter OTP',
  feature_brands: "Featured brands",
  explore_more: 'Explore more',
  next: 'Next',
  previous: 'Previous',
  type_answer: 'Type your answer...',
  add: 'ADD',
  not_specified: 'Not satisfied',
  very_specified: 'Very satisfied',
  select_from_dropdown: "Select from dropdown",
  submit: 'Submit',
  select_time: 'Select Time',
  select_date: "Select Date",
  spinWheelListHeader: "Wheel of Fortune",
  spinWheelListCaption: "Play and win a chance to earn some points, coupons & amazing offers",
  buttonText: "Spin Now",
  earnToUnlockHeader: "Wallet",
  remainingAttempts: "attempts remaining : ",
  dailyWheelBonanza: "Suprise Daily Wheel Bonanza",
  earnLoyaltyHub: "EARN AT LOYALTY HUB",
  earn: "EARN ",
  unlock: " 100 TO UNLOCK",
  loyalty_hub: 'Loyalty Hub',
  earn_zone: 'Earn Zone',
  view_all: "View All",
  dine_win: "Dine & Win",
  dine_win_like_never_before: 'Dine & Win Like Never Before!',
  running_campaigns: 'Running Campaigns',
  enter_ur_mobile_to_continue: "Enter your mobile to continue",
  your_mobile_number: "Your phone number",
  verify_mobile: 'Verify Mobile',
  verify_otp: 'Verify OTP',
  enter_otp: 'Enter OTP',
  sent_to: "Sent to",
  resend_otp: 'Resend OTP',
  select_country: 'Select country',
  which_country_are_u_looking: "Which country are you looking for?",
  submit: "Submit",
  select_time: "Select Time",
  select_date: "Select Date",
  spinWheelListHeader: "Wheel of Fortune",
  spinWheelListCaption:
    "Play and win a chance to earn some points, coupons & amazing offers",
  buttonText: "Spin Now",
  earnToUnlockHeader: "Wallet",
  remainingAttempts: "attempts remaining : ",
  dailyWheelBonanza: "Suprise Daily Wheel Bonanza",
  earnLoyaltyHub: "EARN AT LOYALTY HUB",
  earn: "EARN ",
  unlock: " 100 TO UNLOCK",
  tnc: "Terms & Conditions",
  curatedCoupons: "Curated Coupons",
  couponExplore: "Coupons to Explore",
  answer_cannot_blank: "Answer cannot be blank",
  specialOffers: "Special Offers",
  name: "Name",
  phoneNumber: "Phone Number",
  email: "Email",
  gender: "Gender",
  birthday: "Birthday",
  anniversay: "Anniversay",
  genderPlaceholder: "F/M/O",
  datePlaceholder: "DD / MM / YYYY",
  commonModalHeading: "Notification",
  save: "Save",
  btnTextVerification: "SEND VERIFICATION LINK",
  keepAccount: "KEEP ACCOUNT",
  deleteAccount: "DELETE ACCOUNT",
  which_store_u_looking_for:'Which store are you looking for?',
  coupon_for_you:'Coupons for you',
  make_shopping_enjoyable:'Make Shopping Enjoyable',
  explore_more_coupon:"Explore more coupons",
  feature_brands_at_forum:'Featured Brands at FORUM',
  delightful_reward_together:"Delightful rewards for sticking together",
  reward_for_you:"Rewards for you",
  explore_more_rewards:"Explore more rewards",
  stay_updated:'Stay Updated',
}

export default strings
